The ``1-my_list`` module
======================

Using ``print_sorted``
--------------------

Importing the function from the module:
        >>> My_list = __import__("1-my_list").MyList

Checking print_sorted
		>>> my_test_list = My_list([1, 4, 2, 3, 5])
		>>> my_test_list.print_sorted()
		[1, 2, 3, 4, 5]

Checking regular print
		>>> my_test_list = My_list([1, 4, 2, 3, 5])
		>>> print(my_test_list)
		[1, 4, 2, 3, 5]

Checking sorted method with 1 argument
		>>> my_test_list.print_sorted([1, 6, 4])
		Traceback (most recent call last):
			...
		TypeError: print_sorted() takes 1 positional argument but 2 were given

Checking sorted method with 2 arguments
		>>> my_test_list.print_sorted([1, 6, 4], 56)
		Traceback (most recent call last):
			...
		TypeError: print_sorted() takes 1 positional argument but 3 were given

Checking empty list case
		>>> my_test_list = My_list()
		>>> my_test_list.print_sorted()
		[]

Checking negative elements
		>>> my_test_list = My_list([-1, -90, -54, 0])
		>>> my_test_list.print_sorted()
		[-90, -54, -1, 0]

Checking elements in order
		>>> my_test_list = My_list([5, 78, 102, 1000])
		>>> my_test_list.print_sorted()
		[5, 78, 102, 1000]

Checking test append
		>>> my_test_list.append(89)
		>>> my_test_list.print_sorted()
		[5, 78, 89, 102, 1000]

Checking list with only one element
		>>> my_test_list = My_list([90])
		>>> my_test_list.print_sorted()
		[90]

Checking class type test:
		>>> type(my_test_list) == My_list
		True

Checking instance method:
		>>> type(My_list.__dict__['print_sorted'])
		<class 'function'>

Checking heritage
		>>> issubclass(type(my_test_list), list)
		True

Checking instance test
		>>> my_test_list = My_list()
		>>> isinstance(my_test_list, list)
		True

Sorted list with a sublist
		>>> my_test_list = My_list([34, [5, 9, 12]])
		>>> my_test_list.print_sorted(my_test_list)
		Traceback (most recent call last):
			...
		TypeError: print_sorted() takes 1 positional argument but 2 were given

Every TypeError
		>>> my_test_list.print_sorted() #doctest: +IGNORE_EXCEPTION_DETAIL
		Traceback (most recent call last):
			...
		TypeError:
